%Cruzeiro do Sul
%Disciplina: PIC EM CIÊNCIA DA COMPUTAÇÃO IV
%Aluno: Athus Kuntler Magalhães da Cruz
%Atividade: Construir um chatbot especialista em responder a perguntas sobre redes de computadores

:- initialization(main).
  % Base de Dados 1
  base_de_dados('rede de computadores','Rede de computadores ou redes de dados, na informática e na telecomunicação é um conjunto de dois ou mais dispositivos eletrônicos de computação interligados por um sistema de comunicação digital, guiados por um conjunto de regras para compartilhar entre si informação, serviços e, recursos físicos e lógicos.').
  base_de_dados('classificação de redes','Um critério para classificar as redes é sua escala, organizando por seu tamanho físico. As aplicações pessoais são redes destinadas a uma pessoa. Podemos considerar o mouse e o teclado do computador como uma rede pessoal. Os smart-phones são classificados na categoria de redes pessoais. Entretanto, existem redes de maior abrangência que podem ser classificadas em redes locais, metropolitanas e geograficamente distribuídas (ou remotas).').
  base_de_dados('roteador','Um roteador é um dispositivo que encaminha pacotes de dados entre redes de computadores, criando um conjunto de redes de sobreposição. Um roteador é conectado a duas ou mais linhas de dados de redes diferentes.').
  base_de_dados('placa de rede','Uma placa de rede é um dispositivo de hardware responsável pela comunicação de um computador em uma rede de computadores. A placa de rede controla o envio e recebimento de dados de um computador conectado a uma rede, através de ondas eletromagnéticas, cabos metálicos ou cabos de fibra óptica.').
  base_de_dados('modem','Um modem é um dispositivo de hardware que converte dados em um formato adequado para um meio de transmissão de forma que possam ser transmitidos de um computador para outro.').
  base_de_dados('repetidor','repetidor é um equipamento eletrônico utilizado para a interligação de redes idênticas, pois eles absorvem eletricamente os sinais e os retransmite pelo mesmo segmento no meio físico. Um repetidor atua na camada física do Modelo OSI.').
  base_de_dados('Switch','Os dispositivos de interconexão têm duas áreas de atuação nas redes telemáticas. Em um segundo nível estariam os switches, que são responsáveis ​​pela interconexão de equipamentos dentro de uma mesma rede, ou o que é o mesmo, são os dispositivos que, junto com a fiação, constituem as redes locais ou LAN.').
  base_de_dados('LAN','Uma rede de área local em computação consiste de uma rede de computadores utilizada na interconexão de equipamentos processadores, cuja finalidade é a troca de dados.').
  base_de_dados('MAN','MAN significa “Metropolitan Area Network”, ou seja, rede de área metropolitana. São projetadas justamente para interconectar sistemas de cidades próximas ou de uma região metropolitana. Este tipo de rede é caracterizado por ter um alcance maior que as do tipo LANs.').
  base_de_dados('WAN','Uma rede de longa distância ou rede de grande extensão é uma rede de computadores que abrange uma grande área geográfica, com frequência um país ou continente. Difere, assim, da Rede pessoal, da Rede de área local e da Rede de área metropolitana.').
  base_de_dados('internet','A internet é o conjunto de redes de computadores que, espalhados por todas as regiões do planeta, conseguem trocar dados e mensagens utilizando um protocolo comum. Este protocolo compartilhado pela internet é capaz de unir vários usuários particulares, entidades públicas e empresariais em um mesmo acesso.').
  base_de_dados('correio eletrônico','O correio eletrônico ou e-mail é uma ferramenta usada para enviar e receber mensagens de maneira instantânea através da Internet. É um serviço gratuito onde é possível incluir fotografias ou arquivos de todo tipo nas mensagens.').
  base_de_dados('cabo coaxial','O cabo coaxial é um tipo de cabo usado para transmitir sinais. Este tipo de cabo é constituído por um fio de cobre condutor revestido por um material isolante e rodeado de uma blindagem.').
  base_de_dados('cabo de par trançado','O Cabo por par trançado é um tipo de cabo que possui pares de fios entrelaçados um ao redor do outro para cancelar as interferências eletromagnéticas. Foi inventado por Alexander Graham Bell no final do século XIX').
  base_de_dados('fibra óptica','Fibra óptica é um filamento flexível e transparente fabricado a partir de vidro ou plástico extrudido e que é utilizado como condutor de elevado rendimento de luz, imagens ou impulsos codificados. Tem diâmetro de alguns micrometros, ligeiramente superior ao de um fio de cabelo humano.').
  base_de_dados('radiofrequência','Radiofrequência é a faixa de frequência que abrange aproximadamente de 3 kHz a 300 GHz e que corresponde à frequência das ondas de rádio. RF geralmente se refere a oscilações eletromagnéticas ao invés de mecânicas nessa faixa de frequência, embora existam sistemas mecânicos em RF.').
  base_de_dados('topologias de redes','A topologia de rede é o canal no qual o meio de rede está conectado aos computadores e outros componentes de uma rede de computadores. Essencialmente, é a estrutura topológica da rede, e pode ser descrito física ou logicamente. Há várias formas nas quais se podem organizar a interligação entre cada um dos nós da rede.').
  base_de_dados('topologia parcialmente ligada','É similar a topologia totalmente ligada. O custo dessa rede é menor do que a totalmente ligada devido a quantidade de ligações ser menor, porém a mensagem nem sempre é enviada de maneira direta, perdendo assim desempenho.').
  base_de_dados('topologia em barramento','Também chamada de topologia de backbone, bus ou linha, orienta os dispositivos ao longo de um único cabo que vai de uma extremidade da rede à outra. Os dados fluirão ao longo do cabo conforme ele se desloca até seu destino.').
  base_de_dados('topologia ponto a ponto','Topologia ponto a ponto (peer to peer ou p2p) é uma topologia de rede que conecta dois dispositivos diretamente. É usado principalmente para conectar computadores, servidores e impressoras em uma rede.').
  base_de_dados('topologia multiponto','Na topologia Ponto Multiponto, a rede permite o alcance de vários assinantes, limitando o número de roteadores, switches e outros equipamentos que são necessários para o funcionamento de uma rede cabeada.').
  base_de_dados('topologia em estrela','A topologia em estrela é caracterizada por um elemento central que "gerencia" o fluxo de dados da rede, estando diretamente conectado a cada nó, daí surgiu a designação "Estrela". As informações trafegam na rede de um host para o outro.').
  
  % Base de Dados 2
  base_de_dados('ethernet','Ethernet é uma família de tecnologias de rede de computadores com fio comumente usadas em redes de área local, redes de área metropolitana e redes de longa distância. Foi introduzido comercialmente em 1980 e padronizado pela primeira vez em 1983 como IEEE 802.3.').
  base_de_dados('endereçamento na ethernet e quais são os seus serviços','o endereçamento na Ethernet permite que os dispositivos em uma rede local se comuniquem diretamente entre si, identificando exclusivamente cada dispositivo e controlando o fluxo de tráfego de dados na rede.').
  base_de_dados('protocolo MAC','protocolo MAC (Media Access Control) é um conjunto de regras que governam como dispositivos em uma rede compartilham o meio de transmissão de dados. O objetivo principal do protocolo MAC é garantir que apenas um dispositivo possa transmitir dados em um determinado momento, para evitar colisões de dados e garantir que a rede opere de forma eficiente.').
  base_de_dados('padrão gigabit ethernet','O padrão Gigabit Ethernet é uma tecnologia de rede que oferece uma taxa de transmissão de dados de até 1 gigabit por segundo (Gbps), ou seja, 1 bilhão de bits por segundo. É uma evolução do padrão Ethernet original, que suportava taxas de transmissão de até 10 megabits por segundo (Mbps) e posteriormente, 100 Mbps.').
  base_de_dados('metro ethernet','Metro Ethernet é uma tecnologia de rede que se baseia no padrão Ethernet para fornecer serviços de conectividade de alta velocidade em áreas metropolitanas. É uma solução de rede escalável e econômica que permite a transferência de grandes quantidades de dados entre diferentes locais em uma área geográfica limitada.').
  base_de_dados('protocolo TCP/IP','O protocolo TCP/IP (Transmission Control Protocol/Internet Protocol) é um conjunto de protocolos de comunicação utilizado para conectar dispositivos em redes de computadores e permitir a troca de dados entre eles. Ele é a base da internet e é usado em muitas outras redes de computadores em todo o mundo.').
  base_de_dados('protocolos que constituem o TCP','o TCP é composto por vários protocolos que trabalham juntos para fornecer comunicação confiável entre dispositivos em uma rede. O protocolo de controle de transmissão (TCP) é o principal protocolo do TCP e é responsável por dividir, numerar e controlar o fluxo de dados. Além disso, o TCP também inclui outros protocolos, como o protocolo de controle de congestionamento, protocolo de estabelecimento de conexão, protocolo de encerramento de conexão, protocolo de verificação de som e protocolo de temporização.').
  base_de_dados('IGRP','IGRP (Interior Gateway Routing Protocol) é um protocolo de roteamento interno utilizado em redes de computadores para determinar a melhor rota para encaminhar pacotes de dados. Foi desenvolvido pela Cisco Systems e é um protocolo proprietário.').
  base_de_dados('EIGRP','EIGRP (Enhanced Interior Gateway Routing Protocol) é um protocolo de roteamento avançado, desenvolvido pela Cisco Systems, que é usado para determinar a melhor rota para enviar pacotes de dados em uma rede. É um protocolo de roteamento híbrido que combina elementos de protocolos de roteamento de vetor de distância e de estado de link.').
  base_de_dados('SMTP','SMTP (Simple Mail Transfer Protocol) é um protocolo de comunicação utilizado para enviar e-mails pela Internet. É um protocolo padrão da camada de aplicação do modelo OSI, que define como os servidores de e-mail e outros agentes de transferência de correio (MTAs) devem enviar e receber e-mails.').
  base_de_dados('telnet','Telnet é um protocolo de rede que permite a conexão remota a um computador ou dispositivo de rede através de uma rede TCP/IP. Ele permite que um usuário se conecte a um servidor ou dispositivo remoto e execute comandos como se estivesse usando a linha de comando localmente.').
  base_de_dados('FTP','FTP (File Transfer Protocol) é um protocolo de rede que permite a transferência de arquivos entre computadores na Internet. Ele é amplamente utilizado para transferir arquivos de um servidor para um cliente ou de um cliente para um servidor.').
  base_de_dados('http','HTTP (Hypertext Transfer Protocol) é um protocolo de comunicação usado para transferir dados pela internet. Ele é a base da World Wide Web e é usado para solicitar e enviar informações entre navegadores web e servidores web.').
  base_de_dados('camada de rede','A camada de rede é a terceira camada do modelo OSI (Open Systems Interconnection) e é responsável por fornecer serviços de roteamento e encaminhamento de pacotes de dados entre dispositivos em uma rede.').
  base_de_dados('IPv4','IPv4 é a quarta versão do protocolo de Internet (Internet Protocol), que é a base da comunicação na Internet. O IPv4 usa um endereço de 32 bits para identificar dispositivos em uma rede e é o protocolo mais amplamente usado na internet.').
  base_de_dados('ICMP','ICMP (Internet Control Message Protocol) é um protocolo da camada de rede do modelo OSI (Open Systems Interconnection) que é usado para gerenciar mensagens de erro e controle de fluxo na Internet.').
  
  % 3a etapa: regras
  main :-
   repeat,
   write('Escreva o termo que deseja pesquisar sobre Rede de Computadores(Entre aspas simples, seguido de ponto e enter'),nl,
   read(Input),nl,
   base_de_dados(Input,Output),nl,
   write(Output),nl,nl.